# Generated by Django 3.1.4 on 2021-10-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('number_of_tracks', models.CharField(default='', max_length=10, unique=True)),
                ('user_id', models.CharField(default='', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('artist_id', models.CharField(default='', max_length=10)),
                ('album_id', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
